# Generated by Django 3.2.7 on 2025-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_users', '0003_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'indian'), ('CH', 'chinese'), ('IT', 'italian'), ('MX', 'mexican'), ('GR', 'greek'), ('FF', 'fastfood'), ('OT', 'other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
